# Generated by Django 3.1.7 on 2021-04-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('url', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('content', models.JSONField()),
            ],
        ),
    ]
